version: '3.8'
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: crypto-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: